import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Menu, Moon } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Social } from "@/components/common/social";

const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PWR Chain Mock",
  description: "Generated by create next app with tailwind preset",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={space.className}>
        <nav className="md:h-20 h-16 flex items-center shadow-header w-full lg:px-20 xl:px-24 z-50 bg-white px-4">
          <Link href="/">
            <Image src="/logo.svg" width={126} height={22} alt="logo" />
          </Link>
          <div className="justify-between md:flex mx-auto items-center max-w-lg w-full gap-x-2 font-medium hidden">
            <Link href="/">Explore</Link>
            <Link href="/">Blockchain</Link>
            <Link href="/">Tokens</Link>
            <Link href="/">NFTs</Link>
          </div>
          <div className="flex md:gap-x-4 gap-x-2 ml-auto md:ml-0">
            <Button className="hidden md:flex" variant={"secondary"}>
              Connect
            </Button>
            <Button variant="ghost" className="md:hidden flex">
              <Menu />
            </Button>
            <Button variant="secondary-blue">Get Wallet</Button>
            <Button variant="link" className="hidden md:flex p-0">
              <Moon className="fill-icon stroke-icon" />
            </Button>
          </div>
        </nav>
        {children}
        <footer className="bg-brand-bg md:py-20 md:px-12 p-4">
          <div className="md:max-w-6xl mx-auto">
            <div className="grid md:grid-cols-2 md:pb-16 pb-10 grid-cols-1 gap-y-4 md:gap-y-0">
              <div className="flex flex-col gap-y-6">
                <Link href="/" className="font-bold block">
                  <Image src="/logo.svg" width={126} height={22} alt="logo" />
                </Link>
                <ol className="md:inline-flex gap-x-8 gap-y-4 grid grid-cols-2 px-4 md:gap-y-0">
                  <li>
                    <Link href="/explore">Explore</Link>
                  </li>
                  <li>
                    <Link href="/transactions">Transactions</Link>
                  </li>
                  <li>
                    <Link href="/nodes">Nodes</Link>
                  </li>
                  <li>
                    <Link href="/wallet">PWR Wallet</Link>
                  </li>
                </ol>
              </div>
              <div className="flex items-end md:gap-x-4 md:justify-end gap-x-2 justify-between">
                <div className="flex flex-col gap-y-1 w-full md:w-fit">
                  <label htmlFor="newsletter" className="max-w-fit">
                    Join our newsletter
                  </label>
                  <Input
                    id="newsletter"
                    placeholder="Enter your email"
                    autoComplete="email"
                    title="email"
                  />
                </div>
                <Button variant={"secondary-blue"} className="">
                  Subscribe
                </Button>
              </div>
            </div>
            <hr />
            <div className="grid grid-cols-2 lg:max-w-fit max-w-full gap-4 py-4 px-2 md:grid-cols-3  place-items-center">
              <Social
                label="Join our Twitter"
                href="/"
                icon={
                  <Image
                    src="/icons/twitter.svg"
                    height={24}
                    width={24}
                    alt="twitter"
                  />
                }
              />
              <Social
                label="Join our Telegram"
                href="/"
                icon={
                  <Image
                    alt="telegram"
                    src="/icons/telegram.svg"
                    height={24}
                    width={24}
                  />
                }
              />
              <Social
                label="Join our Discord"
                href="/"
                icon={
                  <Image
                    src="/icons/discord.svg"
                    height={24}
                    width={24}
                    alt="discord"
                  />
                }
              />
            </div>
            <div className="flex justify-between py-2 flex-col md:flex-row gap-y-1">
              <p className="font-medium text-sm">
                @WOM Protocol Pte. Ltd. All Rights reserved
              </p>
              <ol className="inline-flex gap-x-8 text-brand-secondary text-sm font-medium md:px-8">
                <li className="px-2 py-1">
                  <Link href="/terms">Terms</Link>
                </li>
                <li className="px-2 py-1">
                  <Link href="/privacy">Privacy</Link>
                </li>
              </ol>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
